repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch=main]
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: pretty-format-json
        args: [--autofix]
      - id: check-xml
      - id: debug-statements
      - id: check-added-large-files
      - id: check-case-conflict
      - id: detect-private-key
      - id: requirements-txt-fixer
      - id: detect-aws-credentials

  - repo: https://github.com/myint/autoflake
    rev: b330072a26bb13aea8843f8083cee5332d71f78f
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
          - --expand-star-imports
          - --ignore-init-module-imports

  - repo: https://github.com/timothycrosley/isort
    rev: 5.4.1
    hooks:
      - id: isort
        files: ^(handler|billers|scripts)/

  - repo: https://github.com/ambv/black
    rev: 21.5b1
    hooks:
      - id: black
        language_version: python3.8
        files: ^(handler|billers|scripts)/

  - repo: https://gitlab.com/PyCQA/flake8
    rev: 3.8.2
    hooks:
      - id: flake8
        files: ^(handler|billers|scripts)/

  - repo: https://github.com/resmio/pre-commit-doctoc
    rev: v1.0.0
    hooks:
      - id: doctoc
        args: [--title=## Table of Contents]

  - repo: local
    hooks:
      - id: check-pinned-requirements
        name: Check pinned requirements in requirements.txt
        entry: scripts/check_pinned_requirements.py
        language: system
        files: requirements.txt

default_language_version:
  python: python3.8

fail_fast: false
